services:
  bot:
    build: .
    container_name: vpn_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vpn_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: